# Generated by Django 5.1.3 on 2024-11-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('contract_manager', 'Contract Manager'), ('guest', 'Guest')], default='guest', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
