# Generated by Django 5.1.3 on 2024-11-08 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_template_name', models.CharField(help_text='Name of the contract template', max_length=200)),
                ('serialized_data', models.TextField(help_text='Marshalled serialized data')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the contract', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the contract')),
                ('start_date', models.DateField(help_text='Start date of the contract')),
                ('end_date', models.DateField(blank=True, help_text='End date of the contract', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the contract', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terms', models.TextField(help_text='Terms and conditions of the contract')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total contract amount', max_digits=10)),
                ('attachments', models.FileField(blank=True, help_text='Any associated documents or files', null=True, upload_to='contracts/attachments/')),
                ('owner', models.ForeignKey(help_text='User who owns the contract', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
