# Generated by Django 5.1.3 on 2024-11-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracttemplate',
            name='contract_template_name',
        ),
        migrations.RemoveField(
            model_name='contracttemplate',
            name='serialized_data',
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='data',
            field=models.BinaryField(help_text='Serialized contract template data', null=True),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
