stages:
  - prepare
  - test
  - deploy

before_script:
  - apt-get update && apt-get install -y curl

prepare:
  stage: prepare
  script:
    - echo "Preparing environment..."

test:
  stage: test
  script:
    - echo "Running tests..."
    - echo "No tests defined"

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - echo "No deployment defined"
  only:
    - main